name: Semgrep
on:
  push:
    paths:
      - 'src/shippingservice/**'
jobs:
  semgrep:
    name: Executing semgrep rules
    runs-on: ubuntu-latest
    steps:
      # Fetch project source code
      - name: Checkout
        uses: actions/checkout@v2
      - name: Executing semgrep rules
        uses: ./src/shippingservice/semgrep/.